# Generated by Django 5.2.16 on 2026-08-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alert_councilagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: alert graphic (JPEG/PNG)', null=True, upload_to='alerts/'),
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: logo or storefront photo (JPEG/PNG)', null=True, upload_to='businesses/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: photo/flyer for this event (JPEG/PNG)', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: photo for this news item (JPEG/PNG)', null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='video',
            field=models.FileField(blank=True, help_text='Optional: video clip for this news item (MP4)', null=True, upload_to='news/videos/'),
        ),
    ]
