# Generated by Django 5.2.16 on 2026-08-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alert_image_business_image_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='e.g. Sunny and hot, high of 94°F', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Extended forecast or advisory text')),
                ('sunrise', models.CharField(blank=True, help_text='e.g. 6:12 AM', max_length=20)),
                ('sunset', models.CharField(blank=True, help_text='e.g. 7:48 PM', max_length=20)),
                ('humidity', models.CharField(blank=True, help_text='e.g. 12%', max_length=10)),
                ('wind', models.CharField(blank=True, help_text='e.g. SW 8-15 mph', max_length=100)),
                ('fire_risk', models.CharField(blank=True, help_text='e.g. Moderate', max_length=50)),
                ('temperature_high', models.IntegerField(blank=True, help_text="Today's high (°F)", null=True)),
                ('temperature_low', models.IntegerField(blank=True, help_text="Tonight's low (°F)", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Update',
                'verbose_name_plural': 'Weather Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('general', 'General News'), ('city_works', 'City Works'), ('church', 'Church / Faith'), ('recreation', 'Recreation & Parks'), ('law_enforcement', 'Law Enforcement'), ('health', 'Health & Wellness'), ('education', 'Schools & Education'), ('business', 'Business & Economy'), ('traffic', 'Traffic & Roads'), ('community', 'Community Events')], default='general', help_text='Which section of the app this appears in', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on the home page hero'),
        ),
    ]
