# Generated by Django 5.2.16 on 2026-08-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_weatherinfo_newsitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('elementary', 'Elementary'), ('middle', 'Middle School'), ('high', 'High School'), ('other', 'Other')], default='other', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('home_business', 'Home Business'), ('freelancer', 'Freelancer'), ('local_shop', 'Local Shop'), ('service', 'Service'), ('restaurant', 'Restaurant'), ('business_support', 'Business Support'), ('other', 'Other')], max_length=50),
        ),
    ]
