# Generated by Django 5.2.16 on 2026-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_school_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
