# Generated by Django 5.2.16 on 2026-08-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_school_options_deal_featuredplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='bell_schedule_url',
            field=models.URLField(blank=True, help_text='Link to the school bell schedule document (PDF/DOCX)'),
        ),
        migrations.AddField(
            model_name='school',
            name='calendar_url',
            field=models.URLField(blank=True, help_text='Link to the school/district calendar (page, PDF, or image)'),
        ),
    ]
