# Generated by Django 5.2.16 on 2026-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_discussiontopic_comment_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('general', 'General News'), ('city_works', 'City Works'), ('church', 'Church / Faith'), ('recreation', 'Recreation & Parks'), ('law_enforcement', 'Law Enforcement'), ('health', 'Health & Wellness'), ('education', 'Schools & Education'), ('business', 'Business & Economy'), ('traffic', 'Traffic & Roads'), ('community', 'Community Events'), ('lost_pets', 'Lost Pets'), ('gigs', 'Gigs & Services'), ('neighbor', 'Neighbor Appreciation')], default='general', help_text='Which section of the app this appears in', max_length=50),
        ),
    ]
