# Generated by Django 5.2.16 on 2026-08-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_newsitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Fictional example profile — the app shows a DEMO badge on it'),
        ),
    ]
