# Generated by Django 5.2.17 on 2026-08-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_business_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytip',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('business', 'Business'), ('general', 'General'), ('bug', 'Bug Report'), ('info_update', 'Info Removal/Update'), ('business_promo', 'Business Promotion'), ('freelancer_promo', 'Freelancer Promotion')], max_length=50),
        ),
    ]
