# Generated by Django 5.2.17 on 2026-08-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_communitytip_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('denomination', models.CharField(blank=True, help_text='e.g. Catholic, Baptist, Foursquare', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('service_times', models.TextField(blank=True, help_text='Worship/service days and times')),
                ('events', models.TextField(blank=True, help_text='Recurring or upcoming events this church hosts')),
                ('food_giveaway', models.TextField(blank=True, help_text='Food pantry / giveaway days and times')),
                ('image', models.ImageField(blank=True, null=True, upload_to='churches/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False, help_text='Fictional example — app shows a DEMO badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'ordering': ['name'],
            },
        ),
    ]
