# Generated by Django 5.2.17 on 2026-08-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_church'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('general', 'General News'), ('city_works', 'City Works'), ('church', 'Church / Faith'), ('recreation', 'Recreation & Parks'), ('law_enforcement', 'Law Enforcement'), ('health', 'Health & Wellness'), ('education', 'Schools & Education'), ('business', 'Business & Economy'), ('traffic', 'Traffic & Roads'), ('community', 'Community Events'), ('lost_pets', 'Lost Pets'), ('gigs', 'Gigs & Services'), ('for_sale', 'For Sale & Free'), ('announcements', 'Announcements'), ('neighbor', 'Neighbor Appreciation')], default='general', help_text='Which section of the app this appears in', max_length=50),
        ),
    ]
